import { useState, useEffect, useRef } from "react";

const AREAS = [
  { id:"salut", name:"Ciències de la Salut", icon:"🩺", color:"#E63946" },
  { id:"enginyeria", name:"Enginyeria i Tecnologia", icon:"⚙️", color:"#457B9D" },
  { id:"informatica", name:"Informàtica i Dades", icon:"💻", color:"#2A9D8F" },
  { id:"empresa", name:"Empresa i Economia", icon:"📊", color:"#E9C46A" },
  { id:"dret", name:"Dret i Ciències Polítiques", icon:"⚖️", color:"#8338EC" },
  { id:"educacio", name:"Educació i Pedagogia", icon:"📚", color:"#F4A261" },
  { id:"comunicacio", name:"Comunicació i Mitjans", icon:"🎬", color:"#E76F51" },
  { id:"arts", name:"Arts i Humanitats", icon:"🎨", color:"#BC6C25" },
  { id:"ciencies", name:"Ciències Pures", icon:"🔬", color:"#606C38" },
  { id:"social", name:"Ciències Socials", icon:"🤝", color:"#9B2226" },
  { id:"industria", name:"Indústria i Manteniment", icon:"🔧", color:"#6D6875" },
  { id:"hostaleria", name:"Hostaleria i Turisme", icon:"🍽️", color:"#D4A373" },
  { id:"agro", name:"Agroalimentari i Medi Ambient", icon:"🌿", color:"#588157" },
];

const POND_PDF = "https://img.beteve.cat/wp-content/uploads/2024/05/ponderacions-2026-catalunya-taula-pdf-280524.pdf";
const ACC_GRAU = "Batxillerat + PAU · CFGS (fase admissió voluntària) · Prova >25 anys · >40 amb exp. laboral · >45 anys";
const ACC_CFGS = "Batxillerat · Títol de Tècnic/a (CFGM) · Altre CFGS · Prova d'accés (>18 anys) · Cert. professional";

// pond = matèries que ponderen 0,2 (PAU 2026)
const D = [
  // === GRAUS - SALUT ===
  {name:"Medicina",area:"salut",type:"grau",uni:"UB, UAB, UdL, URV, UPF, UdG, UIC, UVic",af:94,ind:2,sou:41839,ref:30976,sat:8.2,nt:[{u:"UB (Clínic)",n:"12.576"},{u:"UAB",n:"12.398"},{u:"UPF",n:"12.314"}],slug:"medicina",dem:"Molt alta",dur:"6 anys",desc:"Formació completa per exercir com a metge/essa. Especialització via MIR.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques"],provaPAP:null},
  {name:"Infermeria",area:"salut",type:"grau",uni:"UB, UAB, URV, UdL, UdG, UVic, URL, UIC",af:91.1,ind:45,sou:30200,ref:30976,sat:7.8,nt:[{u:"UB",n:"11.256"},{u:"UAB",n:"10.880"},{u:"URV",n:"9.878"}],slug:"infermeria",dem:"Molt alta",dur:"4 anys",desc:"Cures d'infermeria en hospitals, atenció primària, residències i comunitat.",acces:ACC_GRAU,pond:["Biologia","Química","Mat. Aplicades CS"],provaPAP:null},
  {name:"Farmàcia",area:"salut",type:"grau",uni:"UB",af:86.3,ind:68,sou:32500,ref:30976,sat:7.1,nt:[{u:"UB",n:"11.070"}],slug:"farmacia",dem:"Alta",dur:"5 anys",desc:"Ciència del medicament: farmàcia comunitària, hospitalària, indústria i recerca.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques"],provaPAP:null},
  {name:"Odontologia",area:"salut",type:"grau",uni:"UB, UIC",af:85,ind:52,sou:35000,ref:30976,sat:7.5,nt:[{u:"UB",n:"11.850"}],slug:"odontologia",dem:"Alta",dur:"5 anys",desc:"Salut bucodental: diagnòstic, prevenció i tractament de patologies orals.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques"],provaPAP:null},
  {name:"Fisioteràpia",area:"salut",type:"grau",uni:"UB, UAB, URV, UdL, UdG, UVic, URL, UIC",af:82,ind:55,sou:24341,ref:30976,sat:7.9,nt:[{u:"UB",n:"10.578"},{u:"UAB",n:"10.320"},{u:"UdG",n:"9.856"}],slug:"fisioterapia",dem:"Alta",dur:"4 anys",desc:"Rehabilitació física mitjançant tècniques manuals, exercici i teràpies.",acces:ACC_GRAU,pond:["Biologia","Química","Física","Mat. Aplicades CS"],provaPAP:null},
  {name:"Ciències Biomèdiques",area:"salut",type:"grau",uni:"UB, UAB, UPF, UdG",af:72,ind:58,sou:28000,ref:30976,sat:7.3,nt:[{u:"UB",n:"12.180"},{u:"UPF",n:"12.050"},{u:"UAB",n:"11.876"}],slug:"ciencies-biomediques",dem:"Mitjana",dur:"4 anys",desc:"Recerca biomèdica: bases moleculars de malalties i desenvolupament de teràpies.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques","Física"],provaPAP:null},
  {name:"Psicologia",area:"salut",type:"grau",uni:"UB, UAB, URV, UdG, URL, UOC, UVic, UIC",af:74,ind:58,sou:26500,ref:30976,sat:7.6,nt:[{u:"UB",n:"10.250"},{u:"UAB",n:"9.940"},{u:"URV",n:"9.112"}],slug:"psicologia",dem:"Alta",dur:"4 anys",desc:"Comportament humà, salut mental, teràpia, neuropsicologia i recerca.",acces:ACC_GRAU,pond:["Biologia","Matemàtiques","Mat. Aplicades CS"],provaPAP:null},
  {name:"Veterinària",area:"salut",type:"grau",uni:"UAB",af:88,ind:60,sou:28500,ref:30976,sat:7.4,nt:[{u:"UAB",n:"11.040"}],slug:"veterinaria",dem:"Alta",dur:"5 anys",desc:"Salut animal, seguretat alimentària, recerca i salut pública.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques"],provaPAP:null},
  {name:"Nutrició Humana i Dietètica",area:"salut",type:"grau",uni:"UB, URV, UVic, URL",af:70,ind:55,sou:24000,ref:30976,sat:7.2,nt:[{u:"UB",n:"9.230"},{u:"URV",n:"8.436"}],slug:"nutricio-humana-i-dietetica",dem:"Mitjana",dur:"4 anys",desc:"Alimentació saludable, nutrició clínica, esportiva i comunitària.",acces:ACC_GRAU,pond:["Biologia","Química","Mat. Aplicades CS"],provaPAP:null},
  {name:"Logopèdia",area:"salut",type:"grau",uni:"UB, UAB, URV, URL",af:75,ind:50,sou:24500,ref:30976,sat:7.5,nt:[{u:"UAB",n:"9.100"},{u:"UB",n:"8.950"}],slug:"logopedia",dem:"Mitjana",dur:"4 anys",desc:"Trastorns de la comunicació, el llenguatge, la parla i la deglució.",acces:ACC_GRAU,pond:["Biologia","Mat. Aplicades CS"],provaPAP:null},
  // === GRAUS - ENGINYERIA ===
  {name:"Enginyeria Industrial",area:"enginyeria",type:"grau",uni:"UPC, UB, UdG, URV, UdL, UVic",af:82.6,ind:78,sou:34500,ref:30976,sat:7.0,nt:[{u:"UPC (ETSEIB)",n:"10.130"},{u:"UB",n:"9.450"},{u:"UdG",n:"8.200"}],slug:"enginyeria-en-tecnologies-industrials",dem:"Alta",dur:"4 anys",desc:"Gestió i optimització de processos industrials, energia i producció.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Química","Dibuix Tècnic"],provaPAP:null},
  {name:"Enginyeria Mecànica",area:"enginyeria",type:"grau",uni:"UPC, UdG, URV",af:82.4,ind:76,sou:33000,ref:30976,sat:6.9,nt:[{u:"UPC (ETSEIB)",n:"9.580"},{u:"UPC (EPSEVG)",n:"7.524"},{u:"UdG",n:"7.200"}],slug:"enginyeria-mecanica",dem:"Alta",dur:"4 anys",desc:"Disseny, càlcul i fabricació de sistemes mecànics i estructurals.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Dibuix Tècnic","Tecnologia i Enginyeria"],provaPAP:null},
  {name:"Enginyeria Elèctrica",area:"enginyeria",type:"grau",uni:"UPC, URV",af:86.5,ind:80,sou:34000,ref:30976,sat:7.0,nt:[{u:"UPC (ETSEIB)",n:"8.780"},{u:"UPC (EPSEVG)",n:"5.000"}],slug:"enginyeria-electrica",dem:"Alta",dur:"4 anys",desc:"Sistemes elèctrics, energies renovables, instal·lacions i electrònica de potència.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Dibuix Tècnic","Tecnologia i Enginyeria"],provaPAP:null},
  {name:"Enginyeria Química",area:"enginyeria",type:"grau",uni:"UPC, UB, URV",af:82.4,ind:72,sou:32000,ref:30976,sat:6.8,nt:[{u:"UPC",n:"9.350"},{u:"UB",n:"9.100"},{u:"URV",n:"7.500"}],slug:"enginyeria-quimica",dem:"Alta",dur:"4 anys",desc:"Processos químics industrials, medi ambient i nous materials.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Química"],provaPAP:null},
  {name:"Enginyeria Biomèdica",area:"enginyeria",type:"grau",uni:"UB, UPC, UPF",af:80,ind:70,sou:33000,ref:30976,sat:7.2,nt:[{u:"UB",n:"12.740"},{u:"UPC",n:"12.100"},{u:"UPF",n:"11.800"}],slug:"enginyeria-biomedica",dem:"Alta",dur:"4 anys",desc:"Tecnologia aplicada a la medicina: implants, diagnòstic, IA mèdica.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Biologia","Química"],provaPAP:null},
  {name:"Enginyeria Aeroespacial",area:"enginyeria",type:"grau",uni:"UPC",af:85,ind:75,sou:37000,ref:30976,sat:7.3,nt:[{u:"UPC (EETAC)",n:"12.936"},{u:"UPC (ESEIAAT)",n:"11.650"}],slug:"enginyeria-en-tecnologies-aeroespacials",dem:"Alta",dur:"4 anys",desc:"Aeronàutica i espai: disseny d'aeronaus, propulsió i sistemes espacials.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Dibuix Tècnic"],provaPAP:null},
  {name:"Arquitectura",area:"enginyeria",type:"grau",uni:"UPC, URV, URL",af:72,ind:60,sou:28000,ref:30976,sat:7.1,nt:[{u:"UPC (ETSAB)",n:"9.652"},{u:"URV",n:"7.800"}],slug:"arquitectura",dem:"Mitjana",dur:"5 anys",desc:"Projectació, construcció i rehabilitació d'edificis i espais urbans.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Dibuix Tècnic","Dibuix Artístic"],provaPAP:null},
  // === GRAUS - INFORMÀTICA ===
  {name:"Enginyeria Informàtica",area:"informatica",type:"grau",uni:"UPC, UB, UAB, UPF, UdG, URV, UdL, UOC, URL, UVic",af:89.4,ind:93.8,sou:34207,ref:30976,sat:7.0,nt:[{u:"UPC (FIB)",n:"10.870"},{u:"UB",n:"9.750"},{u:"UAB",n:"9.380"}],slug:"enginyeria-informatica",dem:"Molt alta",dur:"4 anys",desc:"Programació, sistemes, xarxes, IA i enginyeria del programari.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Tecnologia i Enginyeria"],provaPAP:null},
  {name:"Ciència i Enginyeria de Dades",area:"informatica",type:"grau",uni:"UPC, UPF, UB",af:87,ind:90,sou:35000,ref:30976,sat:7.2,nt:[{u:"UPC",n:"11.230"},{u:"UPF",n:"11.050"},{u:"UB",n:"10.800"}],slug:"ciencia-i-enginyeria-de-dades",dem:"Molt alta",dur:"4 anys",desc:"Big Data, intel·ligència artificial, machine learning i analítica avançada.",acces:ACC_GRAU,pond:["Matemàtiques","Física"],provaPAP:null},
  {name:"Ciberseguretat",area:"informatica",type:"grau",uni:"UPC, UOC, URL",af:88,ind:88,sou:36000,ref:30976,sat:7.1,nt:[{u:"UPC",n:"10.500"}],slug:null,dem:"Molt alta",dur:"4 anys",desc:"Protecció de sistemes, xarxes i dades. Hacking ètic i forense digital.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Tecnologia i Enginyeria"],provaPAP:null},
  {name:"Intel·ligència Artificial",area:"informatica",type:"grau",uni:"UPC, UPF",af:90,ind:90,sou:37000,ref:30976,sat:7.5,nt:[{u:"UPC",n:"12.100"},{u:"UPF",n:"11.900"}],slug:"intelligencia-artificial",dem:"Molt alta",dur:"4 anys",desc:"Aprenentatge automàtic, visió per computador, PLN i robòtica intel·ligent.",acces:ACC_GRAU,pond:["Matemàtiques","Física"],provaPAP:null},
  {name:"Telecomunicacions",area:"informatica",type:"grau",uni:"UPC, UAB, URV, UPF",af:85,ind:82,sou:33500,ref:30976,sat:6.9,nt:[{u:"UPC (ETSETB)",n:"9.780"},{u:"UAB",n:"8.200"},{u:"UPF",n:"8.100"}],slug:"enginyeria-de-sistemes-de-telecomunicacio",dem:"Alta",dur:"4 anys",desc:"Comunicacions, xarxes, 5G, IoT i sistemes de transmissió.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Dibuix Tècnic"],provaPAP:null},
  // === GRAUS - EMPRESA ===
  {name:"ADE",area:"empresa",type:"grau",uni:"UB, UAB, UPF, UPC, URV, UdL, UdG, UVic, URL, UOC, UIC",af:74.8,ind:72,sou:29500,ref:30976,sat:6.5,nt:[{u:"UPF",n:"9.622"},{u:"UB",n:"9.450"},{u:"UAB",n:"8.920"}],slug:"administracio-i-direccio-dempreses",dem:"Molt alta",dur:"4 anys",desc:"Gestió d'empreses: finances, màrqueting, recursos humans i estratègia.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Matemàtiques","Economia de l'Empresa"],provaPAP:null},
  {name:"Economia",area:"empresa",type:"grau",uni:"UB, UAB, UPF, URV, UdG",af:73,ind:70,sou:29000,ref:30976,sat:6.6,nt:[{u:"UPF",n:"9.350"},{u:"UB",n:"8.900"},{u:"UAB",n:"8.200"}],slug:"economia",dem:"Alta",dur:"4 anys",desc:"Anàlisi econòmica, polítiques públiques, mercats i macroeconomia.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Matemàtiques","Economia de l'Empresa"],provaPAP:null},
  {name:"Comptabilitat i Finances",area:"empresa",type:"grau",uni:"UPF, UB, UdL",af:76,ind:74,sou:30500,ref:30976,sat:6.4,nt:[{u:"UPF",n:"8.900"},{u:"UB",n:"8.600"}],slug:"finances-i-comptabilitat",dem:"Alta",dur:"4 anys",desc:"Comptabilitat, auditoria, banca, mercats financers i gestió de riscos.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Matemàtiques","Economia de l'Empresa"],provaPAP:null},
  {name:"Turisme",area:"empresa",type:"grau",uni:"UB, UAB, UdG, URV, UdL, UVic",af:68,ind:55,sou:23000,ref:30976,sat:6.3,nt:[{u:"UB",n:"5.000"},{u:"UAB",n:"5.000"}],slug:"turisme",dem:"Mitjana",dur:"4 anys",desc:"Gestió turística, hoteleria, patrimoni cultural i turisme sostenible.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Economia de l'Empresa","Geografia"],provaPAP:null},
  {name:"Màrqueting Digital",area:"empresa",type:"grau",uni:"UPF, UOC, URL, UIC, UVic",af:72,ind:65,sou:27000,ref:30976,sat:6.5,nt:[{u:"UPF",n:"8.500"}],slug:"marqueting-i-comunicacio-digital",dem:"Alta",dur:"4 anys",desc:"Estratègia digital, SEO/SEM, xarxes socials, branding i analítica web.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Economia de l'Empresa"],provaPAP:null},
  // === GRAUS - DRET ===
  {name:"Dret",area:"dret",type:"grau",uni:"UB, UAB, UPF, URV, UdG, UdL, UVic, URL, UOC, UIC",af:71,ind:62,sou:28000,ref:30976,sat:6.6,nt:[{u:"UPF",n:"9.450"},{u:"UB",n:"9.250"},{u:"UAB",n:"8.700"}],slug:"dret",dem:"Alta",dur:"4 anys",desc:"Legislació, tribunals, assessoria jurídica, dret públic i privat.",acces:ACC_GRAU,pond:["Llatí","Mat. Aplicades CS","Economia de l'Empresa"],provaPAP:null},
  {name:"Ciències Polítiques",area:"dret",type:"grau",uni:"UB, UAB, UPF",af:65,ind:55,sou:26000,ref:30976,sat:6.2,nt:[{u:"UPF",n:"8.200"},{u:"UB",n:"7.800"},{u:"UAB",n:"7.600"}],slug:"ciencies-politiques",dem:"Mitjana",dur:"4 anys",desc:"Sistemes polítics, relacions internacionals i polítiques públiques.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Geografia","Llatí"],provaPAP:null},
  {name:"Criminologia",area:"dret",type:"grau",uni:"UB, UAB, UdG, URL, UIC",af:63,ind:52,sou:25000,ref:30976,sat:6.5,nt:[{u:"UB",n:"8.700"},{u:"UAB",n:"8.200"},{u:"UdG",n:"7.500"}],slug:"criminologia",dem:"Mitjana",dur:"4 anys",desc:"Prevenció del delicte, política criminal, victimologia i seguretat.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Biologia","Matemàtiques"],provaPAP:null},
  // === GRAUS - EDUCACIÓ ===
  {name:"Educació Infantil",area:"educacio",type:"grau",uni:"UB, UAB, URV, UdG, UdL, UVic, URL, UIC",af:78,ind:52,sou:24527,ref:30976,sat:7.6,nt:[{u:"UB",n:"7.800"},{u:"UAB",n:"7.500"},{u:"UdG",n:"7.200"}],slug:"educacio-infantil",dem:"Alta",dur:"4 anys",desc:"Formació de mestres de 0 a 6 anys. Creativitat, joc i desenvolupament infantil.",acces:ACC_GRAU+" · ⚠️ Cal superar la PAP (Prova d'Aptitud Personal)",pond:["Mat. Aplicades CS","Biologia"],provaPAP:"Sí (PAP obligatòria)"},
  {name:"Educació Primària",area:"educacio",type:"grau",uni:"UB, UAB, URV, UdG, UdL, UVic, URL, UIC",af:80,ind:54,sou:25000,ref:30976,sat:7.5,nt:[{u:"UB",n:"8.300"},{u:"UAB",n:"8.100"},{u:"UdG",n:"7.600"}],slug:"educacio-primaria",dem:"Alta",dur:"4 anys",desc:"Formació de mestres de 6 a 12 anys. Didàctica, inclusió i innovació educativa.",acces:ACC_GRAU+" · ⚠️ Cal superar la PAP (Prova d'Aptitud Personal)",pond:["Mat. Aplicades CS","Biologia"],provaPAP:"Sí (PAP obligatòria)"},
  {name:"Educació Social",area:"educacio",type:"grau",uni:"UB, UAB, URV, UdG, UdL, UVic",af:72,ind:48,sou:24000,ref:30976,sat:7.2,nt:[{u:"UB",n:"7.500"},{u:"UAB",n:"7.200"}],slug:"educacio-social",dem:"Mitjana",dur:"4 anys",desc:"Intervenció socioeducativa amb col·lectius vulnerables i comunitat.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Geografia"],provaPAP:null},
  {name:"CAFE (Act. Física i Esport)",area:"educacio",type:"grau",uni:"UB, UVic, URL, UdG, UdL",af:73,ind:50,sou:25000,ref:30976,sat:7.3,nt:[{u:"UB (INEFC)",n:"9.100"},{u:"UdG",n:"8.800"},{u:"UdL (INEFC)",n:"8.500"}],slug:"ciencies-de-lactivitat-fisica-i-de-lesport",dem:"Alta",dur:"4 anys",desc:"Entrenament, gestió esportiva, salut i rendiment físic.",acces:ACC_GRAU+" · ⚠️ Cal superar proves d'aptitud física",pond:["Biologia","Física"],provaPAP:"Sí (proves aptitud física)"},
  // === GRAUS - COMUNICACIÓ ===
  {name:"Periodisme",area:"comunicacio",type:"grau",uni:"UAB, UPF, URV, URL, UVic, UIC",af:68,ind:55,sou:23480,ref:30976,sat:6.5,nt:[{u:"UPF",n:"8.100"},{u:"UAB",n:"7.800"},{u:"URV",n:"7.200"}],slug:"periodisme",dem:"Mitjana",dur:"4 anys",desc:"Informació, reporterisme, periodisme digital, dades i investigació.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Llatí","Economia de l'Empresa"],provaPAP:null},
  {name:"Comunicació Audiovisual",area:"comunicacio",type:"grau",uni:"UB, UAB, UPF, URV, URL, UVic, UIC",af:65,ind:50,sou:24000,ref:30976,sat:6.7,nt:[{u:"UPF",n:"8.500"},{u:"UB",n:"8.200"},{u:"UAB",n:"7.800"}],slug:null,dem:"Mitjana",dur:"4 anys",desc:"Producció de TV, cinema, vídeo, ràdio i continguts digitals.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Llatí","Economia de l'Empresa","Fonaments Artístics"],provaPAP:null},
  {name:"Publicitat i RRPP",area:"comunicacio",type:"grau",uni:"UAB, UPF, URV, URL, UVic, UIC",af:67,ind:54,sou:25000,ref:30976,sat:6.5,nt:[{u:"UPF",n:"7.900"},{u:"UAB",n:"7.500"}],slug:"publicitat-i-relacions-publiques",dem:"Mitjana",dur:"4 anys",desc:"Campanyes publicitàries, comunicació corporativa i gestió de marca.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Economia de l'Empresa","Llatí"],provaPAP:null},
  {name:"Videojocs",area:"comunicacio",type:"grau",uni:"UPC, UPF, URL",af:70,ind:60,sou:28000,ref:30976,sat:7.0,nt:[{u:"UPC (CITM)",n:"8.800"},{u:"UPF",n:"8.200"}],slug:"disseny-i-desenvolupament-de-videojocs",dem:"Alta",dur:"4 anys",desc:"Creació de videojocs: programació, art, narrativa i game design.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Dibuix Tècnic"],provaPAP:null},
  // === GRAUS - ARTS ===
  {name:"Belles Arts",area:"arts",type:"grau",uni:"UB",af:58,ind:45,sou:22000,ref:30976,sat:7.2,nt:[{u:"UB",n:"5.000"}],slug:"belles-arts",dem:"Baixa",dur:"4 anys",desc:"Creació artística: pintura, escultura, art digital i conceptual.",acces:ACC_GRAU,pond:["Dibuix Artístic","Fonaments Artístics","DT Arts Plàstiques"],provaPAP:null},
  {name:"Disseny",area:"arts",type:"grau",uni:"UB, UPC, URL, UVic, UIC",af:68,ind:55,sou:25000,ref:30976,sat:7.0,nt:[{u:"UB (Elisava)",n:"7.500"},{u:"UPC",n:"7.200"}],slug:"disseny",dem:"Mitjana",dur:"4 anys",desc:"Disseny gràfic, producte, espais i interacció.",acces:ACC_GRAU,pond:["Dibuix Artístic","Dibuix Tècnic","Fonaments Artístics","DT Arts Plàstiques"],provaPAP:null},
  {name:"Història",area:"arts",type:"grau",uni:"UB, UAB, UdG, UdL, URV",af:60,ind:48,sou:23500,ref:30976,sat:7.0,nt:[{u:"UB",n:"5.000"},{u:"UAB",n:"5.000"}],slug:"historia",dem:"Baixa",dur:"4 anys",desc:"Estudi del passat humà: civilitzacions, conflictes, cultura i patrimoni.",acces:ACC_GRAU,pond:["Llatí","Grec","Història de l'Art","Geografia"],provaPAP:null},
  {name:"Filosofia",area:"arts",type:"grau",uni:"UB, UAB, UdG",af:55,ind:42,sou:22500,ref:30976,sat:7.1,nt:[{u:"UB",n:"5.000"},{u:"UAB",n:"5.000"}],slug:"filosofia",dem:"Baixa",dur:"4 anys",desc:"Pensament crític, ètica, lògica, estètica i filosofia política.",acces:ACC_GRAU,pond:["Llatí","Grec","Mat. Aplicades CS"],provaPAP:null},
  {name:"Traducció i Interpretació",area:"arts",type:"grau",uni:"UAB, UPF, UVic",af:64,ind:48,sou:24500,ref:30976,sat:6.8,nt:[{u:"UAB",n:"5.000"},{u:"UPF",n:"5.000"}],slug:"traduccio-i-interpretacio",dem:"Baixa",dur:"4 anys",desc:"Traducció professional, interpretació simultània i localització.",acces:ACC_GRAU,pond:["Llatí","Grec","Mat. Aplicades CS"],provaPAP:null},
  // === GRAUS - CIÈNCIES ===
  {name:"Matemàtiques",area:"ciencies",type:"grau",uni:"UB, UAB, UPC, UPF",af:86.1,ind:78,sou:33000,ref:30976,sat:7.3,nt:[{u:"UAB",n:"10.500"},{u:"UB",n:"10.200"},{u:"UPC",n:"9.800"}],slug:"matematiques",dem:"Alta",dur:"4 anys",desc:"Àlgebra, anàlisi, probabilitat, estadística i modelització matemàtica.",acces:ACC_GRAU,pond:["Matemàtiques","Física"],provaPAP:null},
  {name:"Física",area:"ciencies",type:"grau",uni:"UB, UAB, UPC",af:80,ind:70,sou:31000,ref:30976,sat:7.4,nt:[{u:"UB",n:"11.800"},{u:"UAB",n:"11.500"},{u:"UPC",n:"10.200"}],slug:"fisica",dem:"Alta",dur:"4 anys",desc:"Mecànica, electromagnetisme, quàntica, astrofísica i física de materials.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Química"],provaPAP:null},
  {name:"Química",area:"ciencies",type:"grau",uni:"UB, UAB, URV, UdG",af:80.9,ind:68,sou:28500,ref:30976,sat:7.0,nt:[{u:"UB",n:"9.200"},{u:"UAB",n:"8.800"},{u:"URV",n:"7.500"}],slug:"quimica",dem:"Mitjana",dur:"4 anys",desc:"Reaccions químiques, materials, anàlisi i síntesi de compostos.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Química","Biologia"],provaPAP:null},
  {name:"Biologia",area:"ciencies",type:"grau",uni:"UB, UAB, UPF, UdG",af:67,ind:55,sou:24772,ref:30976,sat:7.1,nt:[{u:"UB",n:"9.800"},{u:"UAB",n:"9.400"},{u:"UPF",n:"9.200"}],slug:"biologia",dem:"Mitjana",dur:"4 anys",desc:"Vida: ecologia, genètica, zoologia, botànica i biologia molecular.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques"],provaPAP:null},
  {name:"Biotecnologia",area:"ciencies",type:"grau",uni:"UB, UAB, UdG, UVic",af:72,ind:60,sou:27000,ref:30976,sat:7.0,nt:[{u:"UB",n:"10.800"},{u:"UAB",n:"10.500"},{u:"UdG",n:"9.500"}],slug:"biotecnologia",dem:"Alta",dur:"4 anys",desc:"Aplicació de la biologia a indústria, alimentació, farmàcia i medi ambient.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques","Física"],provaPAP:null},
  {name:"Estadística",area:"ciencies",type:"grau",uni:"UB, UPC",af:85,ind:82,sou:33000,ref:30976,sat:6.9,nt:[{u:"UPC",n:"9.500"},{u:"UB",n:"9.200"}],slug:"estadistica",dem:"Alta",dur:"4 anys",desc:"Anàlisi de dades, probabilitat, models estadístics i bioestadística.",acces:ACC_GRAU,pond:["Matemàtiques","Mat. Aplicades CS"],provaPAP:null},
  {name:"Ciències Ambientals",area:"ciencies",type:"grau",uni:"UB, UAB, UdG",af:65,ind:52,sou:25000,ref:30976,sat:7.0,nt:[{u:"UAB",n:"7.500"},{u:"UB",n:"7.200"}],slug:"ciencies-ambientals",dem:"Mitjana",dur:"4 anys",desc:"Medi ambient, sostenibilitat, canvi climàtic i gestió de recursos naturals.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques","Geografia"],provaPAP:null},
  // === GRAUS - SOCIAL ===
  {name:"Treball Social",area:"social",type:"grau",uni:"UB, UAB, URV, UdG, UdL, UVic, URL",af:82.2,ind:48,sou:25000,ref:30976,sat:7.2,nt:[{u:"UB",n:"8.200"},{u:"UAB",n:"7.800"},{u:"UdG",n:"7.500"}],slug:"treball-social",dem:"Alta",dur:"4 anys",desc:"Intervenció social amb persones, famílies i comunitats vulnerables.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Geografia"],provaPAP:null},
  {name:"Sociologia",area:"social",type:"grau",uni:"UB, UAB",af:65,ind:52,sou:25500,ref:30976,sat:6.6,nt:[{u:"UB",n:"7.800"},{u:"UAB",n:"7.200"}],slug:"sociologia",dem:"Mitjana",dur:"4 anys",desc:"Estructura social, desigualtats, demografia i investigació social.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Geografia","Matemàtiques"],provaPAP:null},
  {name:"Antropologia Social i Cultural",area:"social",type:"grau",uni:"UB, UAB",af:58,ind:45,sou:23000,ref:30976,sat:7.0,nt:[{u:"UB",n:"6.500"},{u:"UAB",n:"5.750"}],slug:null,dem:"Baixa",dur:"4 anys",desc:"Diversitat cultural, etnografia, globalització i identitats.",acces:ACC_GRAU,pond:["Llatí","Geografia","Mat. Aplicades CS"],provaPAP:null},
  {name:"Relacions Internacionals",area:"dret",type:"grau",uni:"UAB, URL, UPF",af:67,ind:56,sou:27000,ref:30976,sat:6.8,nt:[{u:"UAB",n:"10.100"},{u:"UPF",n:"9.800"}],slug:"relacions-internacionals",dem:"Alta",dur:"4 anys",desc:"Diplomàcia, cooperació, organismes internacionals i geopolítica.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Geografia","Llatí","Economia de l'Empresa"],provaPAP:null},
  {name:"Relacions Laborals",area:"social",type:"grau",uni:"UB, UAB, URV, UdG, UdL",af:72,ind:55,sou:25500,ref:30976,sat:6.5,nt:[{u:"UB",n:"5.000"},{u:"UAB",n:"5.000"}],slug:"relacions-laborals",dem:"Mitjana",dur:"4 anys",desc:"Dret laboral, recursos humans, negociació col·lectiva i seguretat social.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Economia de l'Empresa"],provaPAP:null},
  {name:"Gestió i Administració Pública",area:"dret",type:"grau",uni:"UB, UAB, UPF, UdG",af:68,ind:55,sou:26500,ref:30976,sat:6.4,nt:[{u:"UB",n:"5.000"},{u:"UPF",n:"7.200"}],slug:"gestio-i-administracio-publica",dem:"Baixa",dur:"4 anys",desc:"Gestió pública, polítiques públiques, administració d'institucions.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Economia de l'Empresa","Llatí"],provaPAP:null},
  {name:"Hª, Política i Economia Contemporànies",area:"dret",type:"grau",uni:"UAB",af:65,ind:52,sou:27000,ref:30976,sat:7.0,nt:[{u:"UAB",n:"8.500"}],slug:"historia-politica-i-economia-contemporanies",dem:"Mitjana",dur:"4 anys",desc:"Grau interdisciplinari (3 facultats UAB): història, ciència política, sociologia i economia del món contemporani. En anglès. Mencions: Hª i Polítiques, Polítiques i Economia, Economia i Hª.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Geografia","Matemàtiques","Economia de l'Empresa"],provaPAP:null},
  {name:"Filosofia, Política i Economia (PPE)",area:"dret",type:"grau",uni:"UPF, UAB (Aliança 4U: UAM, UC3M)",af:68,ind:55,sou:28000,ref:30976,sat:7.1,nt:[{u:"UPF",n:"9.500"}],slug:"filosofia-politica-i-economia",dem:"Alta",dur:"4 anys",desc:"PPE: tradició Oxford. Filosofia, ciència política i economia des d'una perspectiva global. 1r any a BCN (UPF+UAB), 2n a Madrid (UAM+UC3M).",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Matemàtiques","Llatí","Economia de l'Empresa"],provaPAP:null},
  // HUMANITATS I FILOLOGIES
  {name:"Humanitats",area:"arts",type:"grau",uni:"UPF, UOC, UdG",af:55,ind:40,sou:22000,ref:30976,sat:6.8,nt:[{u:"UPF",n:"5.000"},{u:"UdG",n:"5.000"}],slug:"humanitats",dem:"Baixa",dur:"4 anys",desc:"Formació interdisciplinària: literatura, filosofia, art, història i pensament crític.",acces:ACC_GRAU,pond:["Llatí","Grec","Història de l'Art","Mat. Aplicades CS"],provaPAP:null},
  {name:"Estudis Anglesos",area:"arts",type:"grau",uni:"UB, UAB, UdG, UdL",af:65,ind:50,sou:24000,ref:30976,sat:6.8,nt:[{u:"UB",n:"5.000"},{u:"UAB",n:"5.000"}],slug:"estudis-anglesos",dem:"Baixa",dur:"4 anys",desc:"Llengua, literatura i cultura angleses. Lingüística i estudis culturals.",acces:ACC_GRAU,pond:["Llatí","Grec","Mat. Aplicades CS"],provaPAP:null},
  {name:"Filologia Hispànica",area:"arts",type:"grau",uni:"UB, UAB",af:60,ind:48,sou:23500,ref:30976,sat:6.7,nt:[{u:"UB",n:"5.000"},{u:"UAB",n:"5.000"}],slug:"filologia-hispanica",dem:"Baixa",dur:"4 anys",desc:"Llengua i literatura espanyoles: lingüística, crítica literària i edició.",acces:ACC_GRAU,pond:["Llatí","Grec","Mat. Aplicades CS"],provaPAP:null},
  {name:"Filologia Catalana",area:"arts",type:"grau",uni:"UB, UAB, UdG, UdL, URV, UVic",af:62,ind:50,sou:24000,ref:30976,sat:7.0,nt:[{u:"UB",n:"5.000"},{u:"UAB",n:"5.000"}],slug:"filologia-catalana",dem:"Baixa",dur:"4 anys",desc:"Llengua i literatura catalanes: lingüística, crítica literària i edició.",acces:ACC_GRAU,pond:["Llatí","Grec","Mat. Aplicades CS"],provaPAP:null},
  {name:"Estudis Literaris",area:"arts",type:"grau",uni:"UB",af:55,ind:42,sou:22500,ref:30976,sat:7.0,nt:[{u:"UB",n:"5.000"}],slug:"estudis-literaris",dem:"Baixa",dur:"4 anys",desc:"Teoria literària, literatura comparada, crítica i creació literària.",acces:ACC_GRAU,pond:["Llatí","Grec"],provaPAP:null},
  {name:"Arqueologia",area:"arts",type:"grau",uni:"UB, UAB",af:58,ind:45,sou:22500,ref:30976,sat:7.1,nt:[{u:"UB",n:"5.000"},{u:"UAB",n:"5.000"}],slug:"arqueologia",dem:"Baixa",dur:"4 anys",desc:"Excavacions, patrimoni, civilitzacions antigues i cultura material.",acces:ACC_GRAU,pond:["Llatí","Grec","Història de l'Art","Geografia"],provaPAP:null},
  {name:"Història de l'Art",area:"arts",type:"grau",uni:"UB, UAB, UdG",af:56,ind:42,sou:22000,ref:30976,sat:7.0,nt:[{u:"UB",n:"5.000"},{u:"UAB",n:"5.000"}],slug:"historia-de-lart",dem:"Baixa",dur:"4 anys",desc:"Art, patrimoni cultural, museus, crítica i gestió cultural.",acces:ACC_GRAU,pond:["Història de l'Art","Llatí","Grec","Fonaments Artístics"],provaPAP:null},
  {name:"Musicologia",area:"arts",type:"grau",uni:"UAB",af:55,ind:40,sou:22000,ref:30976,sat:7.2,nt:[{u:"UAB",n:"5.000"}],slug:"musicologia",dem:"Baixa",dur:"4 anys",desc:"Anàlisi musical, història de la música, etnomusicologia i crítica.",acces:ACC_GRAU,pond:["Anàlisi Musical","Hª Música i Dansa","Llatí"],provaPAP:null},
  {name:"Conservació i Restauració",area:"arts",type:"grau",uni:"UB",af:60,ind:48,sou:23000,ref:30976,sat:7.3,nt:[{u:"UB",n:"5.000"}],slug:null,dem:"Baixa",dur:"4 anys",desc:"Restauració de pintura, escultura, document gràfic i patrimoni.",acces:ACC_GRAU,pond:["Dibuix Artístic","Fonaments Artístics","Química"],provaPAP:null},
  {name:"Cinematografia",area:"comunicacio",type:"grau",uni:"UB (ESCAC)",af:60,ind:48,sou:24000,ref:30976,sat:7.2,nt:[{u:"UB",n:"5.000"}],slug:"cinematografia",dem:"Mitjana",dur:"4 anys",desc:"Direcció, guió, fotografia, so i muntatge cinematogràfic.",acces:ACC_GRAU,pond:["Fonaments Artístics","Llatí","Mat. Aplicades CS"],provaPAP:null},
  // CIÈNCIES
  {name:"Bioquímica",area:"ciencies",type:"grau",uni:"UB, UAB, URV",af:70,ind:58,sou:26000,ref:30976,sat:7.0,nt:[{u:"UB",n:"10.500"},{u:"UAB",n:"10.200"},{u:"URV",n:"8.800"}],slug:"bioquimica",dem:"Mitjana",dur:"4 anys",desc:"Processos químics de la vida: enzims, metabolisme i biologia molecular.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques"],provaPAP:null},
  {name:"Geologia",area:"ciencies",type:"grau",uni:"UB, UAB",af:62,ind:50,sou:26000,ref:30976,sat:7.0,nt:[{u:"UB",n:"5.000"},{u:"UAB",n:"5.000"}],slug:"geologia",dem:"Baixa",dur:"4 anys",desc:"Mineralogia, paleontologia, tectònica, geologia ambiental i recursos.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Química","Biologia"],provaPAP:null},
  {name:"Ciència i Tecnologia dels Aliments",area:"ciencies",type:"grau",uni:"UB, UAB",af:70,ind:58,sou:26000,ref:30976,sat:6.8,nt:[{u:"UB",n:"7.800"},{u:"UAB",n:"7.200"}],slug:null,dem:"Mitjana",dur:"4 anys",desc:"Seguretat alimentària, processos, qualitat i innovació de productes alimentaris.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques"],provaPAP:null},
  {name:"Nanociència i Nanotecnologia",area:"ciencies",type:"grau",uni:"UAB",af:68,ind:55,sou:27000,ref:30976,sat:6.9,nt:[{u:"UAB",n:"9.200"}],slug:"nanociencia-i-nanotecnologia",dem:"Mitjana",dur:"4 anys",desc:"Materials a escala nanomètrica, electrònica molecular i bionanotecnologia.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Química"],provaPAP:null},
  {name:"Ciències de la Mar",area:"ciencies",type:"grau",uni:"UB",af:60,ind:48,sou:24000,ref:30976,sat:7.2,nt:[{u:"UB",n:"7.000"}],slug:"ciencies-de-la-mar",dem:"Baixa",dur:"4 anys",desc:"Oceanografia, ecologia marina, recursos pesquers i canvi climàtic.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques","Física"],provaPAP:null},
  // ENGINYERIES EXTRA
  {name:"Enginyeria de Disseny Industrial",area:"enginyeria",type:"grau",uni:"UPC, UdG",af:75,ind:65,sou:30000,ref:30976,sat:7.0,nt:[{u:"UPC (EPSEVG)",n:"8.200"},{u:"UdG",n:"7.500"}],slug:"enginyeria-de-disseny-industrial",dem:"Mitjana",dur:"4 anys",desc:"Disseny de producte, ergonomia, prototipatge i innovació.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Dibuix Tècnic","Disseny"],provaPAP:null},
  {name:"Enginyeria Ambiental",area:"enginyeria",type:"grau",uni:"UPC, UAB",af:72,ind:60,sou:29000,ref:30976,sat:7.0,nt:[{u:"UAB",n:"7.500"},{u:"UPC",n:"7.200"}],slug:"enginyeria-ambiental",dem:"Mitjana",dur:"4 anys",desc:"Tractament d'aigües, gestió de residus, energia i sostenibilitat.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Química","Biologia"],provaPAP:null},
  {name:"Enginyeria de l'Energia",area:"enginyeria",type:"grau",uni:"UPC, UdG",af:78,ind:68,sou:32000,ref:30976,sat:7.1,nt:[{u:"UPC",n:"8.500"},{u:"UdG",n:"7.200"}],slug:"enginyeria-de-lenergia",dem:"Alta",dur:"4 anys",desc:"Generació, distribució i gestió energètica. Renovables i eficiència.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Química"],provaPAP:null},
  {name:"Enginyeria Alimentària",area:"enginyeria",type:"grau",uni:"UPC, UdL",af:74,ind:62,sou:28000,ref:30976,sat:6.8,nt:[{u:"UPC",n:"5.000"},{u:"UdL",n:"5.000"}],slug:"enginyeria-alimentaria",dem:"Mitjana",dur:"4 anys",desc:"Processos industrials d'aliments, biotecnologia alimentària i qualitat.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Química","Biologia"],provaPAP:null},
  {name:"Enginyeria Electrònica",area:"enginyeria",type:"grau",uni:"UPC, UAB, URV",af:84,ind:77,sou:33500,ref:30976,sat:6.9,nt:[{u:"UPC (ETSETB)",n:"9.120"},{u:"UAB",n:"8.200"}],slug:"enginyeria-electronica-industrial-i-automatica",dem:"Alta",dur:"4 anys",desc:"Circuits, microelectrònica, sistemes encastats i robòtica.",acces:ACC_GRAU,pond:["Matemàtiques","Física","Tecnologia i Enginyeria"],provaPAP:null},
  // SALUT EXTRA
  {name:"Teràpia Ocupacional",area:"salut",type:"grau",uni:"UVic",af:78,ind:52,sou:24000,ref:30976,sat:7.5,nt:[{u:"UVic",n:"7.800"}],slug:"terapia-ocupacional",dem:"Mitjana",dur:"4 anys",desc:"Rehabilitació funcional per a la vida diària: salut mental, física i geriàtrica.",acces:ACC_GRAU,pond:["Biologia","Mat. Aplicades CS"],provaPAP:null},
  {name:"Podologia",area:"salut",type:"grau",uni:"UB",af:80,ind:55,sou:26000,ref:30976,sat:7.2,nt:[{u:"UB",n:"8.200"}],slug:"podologia",dem:"Mitjana",dur:"4 anys",desc:"Salut del peu: diagnòstic, tractament biomecànic i cirurgia podològica.",acces:ACC_GRAU,pond:["Biologia","Química"],provaPAP:null},
  {name:"Òptica i Optometria",area:"salut",type:"grau",uni:"UPC",af:82,ind:58,sou:26500,ref:30976,sat:7.0,nt:[{u:"UPC",n:"7.500"}],slug:"optica-i-optometria",dem:"Mitjana",dur:"4 anys",desc:"Salut visual, lents de contacte, optometria clínica i baixa visió.",acces:ACC_GRAU,pond:["Biologia","Física","Matemàtiques","Química"],provaPAP:null},
  {name:"Biologia Humana",area:"salut",type:"grau",uni:"UPF",af:70,ind:55,sou:27000,ref:30976,sat:7.3,nt:[{u:"UPF",n:"11.200"}],slug:"biologia-humana",dem:"Mitjana",dur:"4 anys",desc:"Biologia centrada en l'ésser humà: genètica, neurociència i evolució.",acces:ACC_GRAU,pond:["Biologia","Química","Matemàtiques","Física"],provaPAP:null},
  // EMPRESA EXTRA
  {name:"Empresa Internacional",area:"empresa",type:"grau",uni:"UPF, UAB",af:75,ind:71,sou:30000,ref:30976,sat:6.7,nt:[{u:"UPF",n:"9.800"},{u:"UAB",n:"8.500"}],slug:"empresa-internacional",dem:"Alta",dur:"4 anys",desc:"Comerç internacional, estratègia global i gestió multinacional.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Matemàtiques","Economia de l'Empresa"],provaPAP:null},
  {name:"Logística Empresarial",area:"empresa",type:"grau",uni:"UPF (Tecnocampus)",af:70,ind:62,sou:28000,ref:30976,sat:6.4,nt:[{u:"UPF",n:"5.000"}],slug:"logistica-empresarial",dem:"Mitjana",dur:"4 anys",desc:"Cadena de subministrament, transport, magatzems i operacions globals.",acces:ACC_GRAU,pond:["Mat. Aplicades CS","Economia de l'Empresa"],provaPAP:null},

  // ====== CFGS ======
  {name:"CFGS Laboratori Clínic i Biomèdic",area:"salut",type:"cfgs",uni:"Centres públics i concertats",af:72,ind:64,sou:21000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Anàlisis clíniques, microbiologia, bioquímica i hemoteràpia en laboratoris.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Higiene Bucodental",area:"salut",type:"cfgs",uni:"Centres públics i concertats",af:78,ind:58,sou:20000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Prevenció bucodental, tècniques d'exploració i educació per a la salut oral.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Imatge per al Diagnòstic",area:"salut",type:"cfgs",uni:"Centres públics i concertats",af:80,ind:55,sou:22000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Radiologia, ecografia, ressonància magnètica i medicina nuclear.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Dietètica",area:"salut",type:"cfgs",uni:"Centres públics i concertats",af:62,ind:52,sou:18500,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Planificació de dietes, control alimentari i educació nutricional.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS DAM (Aplicacions Multiplataforma)",area:"informatica",type:"cfgs",uni:"Centres públics i concertats",af:78,ind:72,sou:24000,ref:18500,sat:null,nt:[],slug:null,dem:"Molt alta",dur:"2 anys",desc:"Programació d'apps per a mòbils, escriptori i web. Java, Kotlin, Swift.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS DAW (Aplicacions Web)",area:"informatica",type:"cfgs",uni:"Centres públics i concertats",af:76,ind:70,sou:23000,ref:18500,sat:null,nt:[],slug:null,dem:"Molt alta",dur:"2 anys",desc:"Frontend i backend web: HTML, CSS, JavaScript, PHP, bases de dades.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS ASIX (Sistemes Informàtics)",area:"informatica",type:"cfgs",uni:"Centres públics i concertats",af:75,ind:68,sou:22500,ref:18500,sat:null,nt:[],slug:null,dem:"Molt alta",dur:"2 anys",desc:"Servidors, xarxes, cloud, seguretat informàtica i virtualització.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS IA i Big Data",area:"informatica",type:"cfgs",uni:"Centres públics i concertats",af:74,ind:68,sou:24000,ref:18500,sat:null,nt:[],slug:null,dem:"Molt alta",dur:"2 anys",desc:"Aprenentatge automàtic, anàlisi de dades massives, Python i eines d'IA.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Ciberseguretat en Entorns TI",area:"informatica",type:"cfgs",uni:"Centres públics i concertats",af:76,ind:70,sou:24500,ref:18500,sat:null,nt:[],slug:null,dem:"Molt alta",dur:"Curs espec.",desc:"Seguretat ofensiva i defensiva, pentesting, anàlisi forense digital.",acces:"Cal tenir un CFGS d'Informàtica previ (DAM, DAW o ASIX)",pond:[],provaPAP:null},
  {name:"CFGS Administració i Finances",area:"empresa",type:"cfgs",uni:"Centres públics i concertats",af:65,ind:62,sou:19000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Comptabilitat, fiscalitat, gestió financera i tràmits administratius.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Comerç Internacional",area:"empresa",type:"cfgs",uni:"Centres públics i concertats",af:63,ind:58,sou:20000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Logística internacional, duanes, negociació i operacions import/export.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Màrqueting i Publicitat",area:"empresa",type:"cfgs",uni:"Centres públics i concertats",af:60,ind:55,sou:19000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Plans de màrqueting, investigació de mercats, disseny de campanyes.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Educació Infantil",area:"educacio",type:"cfgs",uni:"Centres públics i concertats",af:68,ind:48,sou:17500,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Atenció a infants de 0 a 3 anys a escoles bressol i llars d'infants.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Integració Social",area:"social",type:"cfgs",uni:"Centres públics i concertats",af:65,ind:50,sou:18000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Mediació social, acompanyament a persones en risc d'exclusió.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Animació Sociocultural",area:"social",type:"cfgs",uni:"Centres públics i concertats",af:58,ind:42,sou:17000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Dinamització comunitària, lleure, activitats culturals i turisme social.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Animacions 3D, Jocs i Entorns Interactius",area:"comunicacio",type:"cfgs",uni:"Centres públics i concertats",af:58,ind:48,sou:20000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Modelat 3D, animació, motors de joc, realitat virtual i VFX.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Producció d'Audiovisuals",area:"comunicacio",type:"cfgs",uni:"Centres públics i concertats",af:54,ind:40,sou:19000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Producció audiovisual, gestió de rodatges, pressupostos i distribució.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Automatització i Robòtica Industrial",area:"enginyeria",type:"cfgs",uni:"Centres públics i concertats",af:82,ind:72,sou:23000,ref:18500,sat:null,nt:[],slug:null,dem:"Molt alta",dur:"2 anys",desc:"Programació de PLC, robòtica, Indústria 4.0 i sistemes automatitzats.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Sistemes Electrotècnics",area:"enginyeria",type:"cfgs",uni:"Centres públics i concertats",af:80,ind:70,sou:22000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Instal·lacions elèctriques, domòtica, automatismes i energies renovables.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Energies Renovables",area:"enginyeria",type:"cfgs",uni:"Centres públics i concertats",af:76,ind:62,sou:22000,ref:18500,sat:null,nt:[],slug:null,dem:"Molt alta",dur:"2 anys",desc:"Energia solar, eòlica, biomassa. Instal·lació, manteniment i gestió.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Mecatrònica Industrial",area:"industria",type:"cfgs",uni:"Centres públics i concertats",af:81,ind:70,sou:23000,ref:18500,sat:null,nt:[],slug:null,dem:"Molt alta",dur:"2 anys",desc:"Manteniment electromecànic, hidràulica, pneumàtica i automatismes.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Disseny en Fabricació Mecànica",area:"industria",type:"cfgs",uni:"Centres públics i concertats",af:79,ind:72,sou:22500,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Disseny de peces amb CAD/CAM, mecanitzat CNC i prototipatge.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Automoció",area:"industria",type:"cfgs",uni:"Centres públics i concertats",af:76,ind:65,sou:21000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Diagnòstic i reparació de vehicles, electrònica i vehicle elèctric.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Química Industrial",area:"ciencies",type:"cfgs",uni:"Centres públics i concertats",af:76,ind:65,sou:22000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Processos químics, control de qualitat, medi ambient i producció.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Laboratori d'Anàlisi",area:"ciencies",type:"cfgs",uni:"Centres públics i concertats",af:72,ind:62,sou:21000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Tècniques analítiques, assaigs de laboratori i control de processos.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Direcció de Cuina",area:"hostaleria",type:"cfgs",uni:"Centres públics i concertats",af:76,ind:52,sou:19500,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Gestió de cuines, elaboració de menús, gastronomia creativa.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Gestió d'Allotjaments Turístics",area:"hostaleria",type:"cfgs",uni:"Centres públics i concertats",af:72,ind:55,sou:19000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Recepció, housekeeping, revenue management i atenció al client.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Paisatgisme i Medi Rural",area:"agro",type:"cfgs",uni:"Centres públics i concertats",af:65,ind:50,sou:19000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Jardineria, disseny de paisatge, gestió forestal i medi ambient.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Processos i Qualitat Ind. Alimentària",area:"agro",type:"cfgs",uni:"Centres públics i concertats",af:72,ind:60,sou:20500,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Seguretat alimentària, control de qualitat i innovació alimentària.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Educació i Control Ambiental",area:"agro",type:"cfgs",uni:"Centres públics i concertats",af:62,ind:48,sou:19000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Educació ambiental, gestió de residus, control de contaminació.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Disseny i Producció Editorial",area:"arts",type:"cfgs",uni:"Centres públics i concertats",af:55,ind:48,sou:18500,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Maquetació, preimpressió, disseny editorial i producció gràfica.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // SANITAT — extres
  {name:"CFGS Pròtesis Dentals",area:"salut",type:"cfgs",uni:"Centres públics i concertats",af:82,ind:60,sou:22000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Disseny i fabricació de pròtesis dentals fixes, removibles i sobre implants.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Anatomia Patològica i Citodiagnòstic",area:"salut",type:"cfgs",uni:"Centres públics i concertats",af:75,ind:58,sou:21000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Preparació de mostres biològiques, anàlisi de teixits i citodiagnòstic.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Audiologia Protètica",area:"salut",type:"cfgs",uni:"Centres públics i concertats",af:78,ind:58,sou:21500,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Exploració audiològica, adaptació d'audiòfons i rehabilitació auditiva.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // ACTIVITATS FÍSIQUES I ESPORTIVES
  {name:"CFGS Ensenyament i Animació Socioesportiva",area:"educacio",type:"cfgs",uni:"Centres públics i concertats",af:65,ind:48,sou:18500,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Dinamització esportiva, animació de grups, activitats recreatives i inclusió.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Condicionament Físic",area:"educacio",type:"cfgs",uni:"Centres públics i concertats",af:63,ind:46,sou:18000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Entrenament personal, fitness grupal, nutrició esportiva i sala de fitness.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // IMATGE PERSONAL
  {name:"CFGS Estètica Integral i Benestar",area:"salut",type:"cfgs",uni:"Centres públics i concertats",af:62,ind:48,sou:17500,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Tractaments facials, corporals, hidrotermals, spa i benestar.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Assessoria d'Imatge Personal i Corporativa",area:"comunicacio",type:"cfgs",uni:"Centres públics i concertats",af:55,ind:42,sou:18000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Consultoria d'imatge, protocol, personal shopper i comunicació visual.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Caracterització i Maquillatge Professional",area:"comunicacio",type:"cfgs",uni:"Centres públics i concertats",af:55,ind:40,sou:18000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Maquillatge artístic, efectes especials, perruqueria per a cinema i teatre.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // COMERÇ I MÀRQUETING — extres
  {name:"CFGS Gestió de Vendes i Espais Comercials",area:"empresa",type:"cfgs",uni:"Centres públics i concertats",af:62,ind:56,sou:18500,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Tècniques de venda, visual merchandising i gestió d'equips comercials.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Transport i Logística",area:"empresa",type:"cfgs",uni:"Centres públics i concertats",af:68,ind:60,sou:20000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Cadena logística, magatzems, transport de mercaderies i duanes.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // SERVEIS SOCIOCULTURALS — extres
  {name:"CFGS Mediació Comunicativa",area:"social",type:"cfgs",uni:"Centres públics i concertats",af:60,ind:45,sou:17500,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Llengua de signes, sistemes alternatius de comunicació i mediació.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Promoció d'Igualtat de Gènere",area:"social",type:"cfgs",uni:"Centres públics i concertats",af:58,ind:42,sou:17500,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Polítiques d'igualtat, prevenció de violència de gènere i coeducació.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // EDIFICACIÓ I OBRA CIVIL
  {name:"CFGS Projectes d'Edificació",area:"enginyeria",type:"cfgs",uni:"Centres públics i concertats",af:70,ind:60,sou:21000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Delineació de projectes de construcció, BIM i documentació tècnica.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Projectes d'Obra Civil",area:"enginyeria",type:"cfgs",uni:"Centres públics i concertats",af:68,ind:58,sou:21000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Topografia, urbanisme, obres lineals i aixecaments cartogràfics.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // FUSTA, MOBLE I SURO
  {name:"CFGS Disseny i Moblament",area:"industria",type:"cfgs",uni:"Centres públics i concertats",af:68,ind:58,sou:20000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Disseny de mobiliari, fusteria, restauració i producció en fusta.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // TÈXTIL, CONFECCIÓ I PELL
  {name:"CFGS Patronatge i Moda",area:"arts",type:"cfgs",uni:"Centres públics i concertats",af:55,ind:45,sou:18000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Disseny de patrons, confecció industrial, moda i tendències tèxtils.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // ENERGIA I AIGUA
  {name:"CFGS Gestió de l'Aigua",area:"agro",type:"cfgs",uni:"Centres públics i concertats",af:72,ind:60,sou:22000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Potabilització, depuració, xarxes de distribució i control de qualitat de l'aigua.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Eficiència Energètica i Energia Solar Tèrmica",area:"enginyeria",type:"cfgs",uni:"Centres públics i concertats",af:74,ind:60,sou:22000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Auditories energètiques, certificació d'edificis i instal·lacions solars tèrmiques.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // TRANSPORT I MANTENIMENT DE VEHICLES — extres
  {name:"CFGS Gestió i Organització de Recursos Naturals i Paisatgístics",area:"agro",type:"cfgs",uni:"Centres públics i concertats",af:62,ind:48,sou:19000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Gestió forestal, espais naturals protegits, inventaris i educació ambiental.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // INSTAL·LACIÓ I MANTENIMENT — extres
  {name:"CFGS Prevenció de Riscos Professionals",area:"industria",type:"cfgs",uni:"Centres públics i concertats",af:70,ind:60,sou:21000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Seguretat laboral, higiene industrial, ergonomia i plans d'emergència.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Instal·lacions Tèrmiques i de Fluids",area:"industria",type:"cfgs",uni:"Centres públics i concertats",af:80,ind:68,sou:22000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Climatització, calefacció, refrigeració i instal·lacions de gas.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // ARTS GRÀFIQUES — extres
  {name:"CFGS Disseny i Gestió de la Producció Gràfica",area:"arts",type:"cfgs",uni:"Centres públics i concertats",af:55,ind:48,sou:19000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Gestió de projectes gràfics, impremta, packaging i producció digital.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // HOSTALERIA — extra
  {name:"CFGS Agències de Viatges i Gestió d'Esdeveniments",area:"hostaleria",type:"cfgs",uni:"Centres públics i concertats",af:65,ind:50,sou:18000,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Viatges combinats, reserves, gestió d'esdeveniments i turisme.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Guia, Informació i Assistència Turístiques",area:"hostaleria",type:"cfgs",uni:"Centres públics i concertats",af:60,ind:42,sou:17500,ref:18500,sat:null,nt:[],slug:null,dem:"Mitjana",dur:"2 anys",desc:"Guiatge turístic, atenció al visitant, patrimoni i informació turística.",acces:ACC_CFGS,pond:[],provaPAP:null},
  {name:"CFGS Direcció de Serveis de Restauració",area:"hostaleria",type:"cfgs",uni:"Centres públics i concertats",af:76,ind:50,sou:19000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Gestió de restaurants, servei de sala, sommelleria i events.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // MARÍTIMOPESQUERA
  {name:"CFGS Transport Marítim i Pesca d'Altura",area:"industria",type:"cfgs",uni:"Centres públics (Arenys, Tarragona)",af:82,ind:62,sou:24000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"2 anys",desc:"Navegació, pesca professional, seguretat marítima i gestió de vaixells.",acces:ACC_CFGS,pond:[],provaPAP:null},
  // INFORMÀTICA — extres
  {name:"CFGS Desenvolupament d'Aplicacions 3D i Videojocs",area:"informatica",type:"cfgs",uni:"Centres públics i concertats",af:65,ind:55,sou:22000,ref:18500,sat:null,nt:[],slug:null,dem:"Alta",dur:"Curs espec.",desc:"Programació de videojocs, motors gràfics, realitat virtual i 3D interactiu.",acces:"Cal tenir un CFGS d'Informàtica previ (DAM o DAW)",pond:[],provaPAP:null},
];

const QS = [
  {id:1,text:"Què t'atreu més quan penses en el teu futur professional?",opts:[{text:"Ajudar persones a millorar la seva salut",areas:["salut"],w:3},{text:"Crear tecnologia que canviï el món",areas:["informatica","enginyeria"],w:3},{text:"Liderar projectes i gestionar equips",areas:["empresa","dret"],w:3},{text:"Expressar-me i crear coses noves",areas:["arts","comunicacio"],w:3}]},
  {id:2,text:"Quina assignatura t'agrada més?",opts:[{text:"Biologia o Química",areas:["salut","ciencies","agro"],w:2},{text:"Matemàtiques o Física",areas:["enginyeria","informatica","ciencies"],w:2},{text:"Economia o Història",areas:["empresa","dret","social"],w:2},{text:"Llengua, Filosofia o Art",areas:["arts","comunicacio","educacio"],w:2}]},
  {id:3,text:"Com prefereixes treballar?",opts:[{text:"En equip, amb contacte directe amb persones",areas:["salut","educacio","social","hostaleria"],w:2},{text:"Resolent problemes tècnics complexos",areas:["enginyeria","informatica","industria","ciencies"],w:2},{text:"Analitzant dades i prenent decisions",areas:["empresa","informatica","dret"],w:2},{text:"De forma creativa i independent",areas:["arts","comunicacio"],w:2}]},
  {id:4,text:"Quin d'aquests temes t'interessa més?",opts:[{text:"Intel·ligència artificial i futur digital",areas:["informatica"],w:3},{text:"Canvi climàtic i sostenibilitat",areas:["ciencies","enginyeria","agro"],w:2},{text:"Justícia social i drets humans",areas:["dret","social","educacio"],w:2},{text:"Gastronomia, viatges o cultura",areas:["hostaleria","arts","comunicacio"],w:2}]},
  {id:5,text:"Què valores més d'una feina?",opts:[{text:"Un bon sou i estabilitat",areas:["informatica","enginyeria","salut","industria"],w:1},{text:"Sentir que faig un impacte positiu",areas:["salut","educacio","social","agro"],w:1},{text:"Creixement professional i reptes",areas:["empresa","dret","enginyeria"],w:1},{text:"Llibertat creativa i flexibilitat",areas:["arts","comunicacio","hostaleria"],w:1}]},
  {id:6,text:"Amb quin perfil t'identifiques més?",opts:[{text:"Científic/a: m'encanta investigar",areas:["ciencies","salut"],w:2},{text:"Tècnic/a: m'agrada construir i reparar",areas:["enginyeria","informatica","industria"],w:2},{text:"Comunicador/a: m'agrada explicar i connectar",areas:["comunicacio","educacio","social"],w:2},{text:"Estrateg/a: m'agrada planificar i decidir",areas:["empresa","dret"],w:2}]},
];

function calc(ans){const s={};AREAS.forEach(a=>s[a.id]=0);ans.forEach(a=>a.areas.forEach(id=>s[id]=(s[id]||0)+a.w));return Object.entries(s).sort((a,b)=>b[1]-a[1]);}
function topD(sc,tf){const top=sc.slice(0,4).map(([id])=>id);const f=D.filter(d=>top.includes(d.area)&&(tf==="tots"||d.type===tf));const w=f.map(d=>({...d,cs:(sc.find(([id])=>id===d.area)?.[1]||0)*10+d.af*0.3+(d.sou/1000)*0.2+(d.sat||6)*2,ar:top.indexOf(d.area)}));w.sort((a,b)=>a.ar-b.ar||b.cs-a.cs);return w.slice(0,15);}
function fmt(n){return n.toLocaleString("ca-ES")+" €";}
function df(s,m){const d=s-m;return{d,p:((d/m)*100).toFixed(1),pos:d>=0};}

function Card({d,expanded,onToggle}){
  const a=AREAS.find(x=>x.id===d.area);const sd=df(d.sou,d.ref);const mx=d.type==="cfgs"?26000:45000;const fp=d.type==="cfgs";
  const sc=d.sat?d.sat>=7.5?"#2A9D8F":d.sat>=6.5?"#E9C46A":"#E63946":null;const ac=d.af>=80?"#2A9D8F":d.af>=65?"#E9C46A":"#E63946";
  const link=d.slug?`https://notesdetall.cat/${d.slug}`:null;
  return <div onClick={onToggle} className="dc" style={{background:"rgba(255,255,255,0.04)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:16,overflow:"hidden",transition:"all 0.3s ease",cursor:"pointer"}}>
    <div style={{padding:"20px 24px"}}>
      <div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",gap:12}}>
        <div style={{flex:1}}>
          <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:6,flexWrap:"wrap"}}>
            <span style={{fontSize:18}}>{a.icon}</span>
            <span style={{fontSize:11,fontWeight:600,color:a.color,textTransform:"uppercase",letterSpacing:"0.08em"}}>{a.name}</span>
            {fp&&<span style={{fontSize:10,fontWeight:700,background:"#457B9D33",color:"#A8DADC",padding:"2px 8px",borderRadius:6}}>FP</span>}
            {d.provaPAP&&<span style={{fontSize:10,fontWeight:700,background:"#E6394633",color:"#E63946",padding:"2px 8px",borderRadius:6}}>Prova específica</span>}
          </div>
          <h3 style={{fontSize:19,fontWeight:700,color:"#F1FAEE",margin:0,fontFamily:"'Playfair Display',serif",lineHeight:1.3}}>{d.name}</h3>
        </div>
        <div style={{display:"flex",flexDirection:"column",alignItems:"flex-end",gap:4}}>
          <span style={{fontSize:21,fontWeight:800,color:"#F1FAEE"}}>{fmt(d.sou)}</span>
          <span style={{fontSize:11,color:"rgba(241,250,238,0.5)"}}>/any {fp?"(6-9m post-títol)":"(4a post-grau)"}</span>
        </div>
      </div>
      <div style={{display:"flex",gap:16,marginTop:14,flexWrap:"wrap"}}>
        <div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:ac}}/><span style={{fontSize:13,color:"rgba(241,250,238,0.7)"}}>Ocupabilitat: <strong style={{color:"#F1FAEE"}}>{d.af}%</strong></span></div>
        {d.sat!==null&&<div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:"50%",background:sc}}/><span style={{fontSize:13,color:"rgba(241,250,238,0.7)"}}>Satisfacció: <strong style={{color:"#F1FAEE"}}>{d.sat}/10</strong></span></div>}
        <span style={{fontSize:12,fontWeight:700,color:sd.pos?"#2A9D8F":"#E63946"}}>{sd.pos?"▲":"▼"} {sd.pos?"+":""}{sd.p}% vs mitjana {fp?"FP":"grau"}</span>
      </div>
    </div>
    {expanded&&<div style={{padding:"0 24px 20px",borderTop:"1px solid rgba(255,255,255,0.06)",paddingTop:16}}>
      <p style={{fontSize:14,color:"rgba(241,250,238,0.7)",lineHeight:1.6,margin:"0 0 16px"}}>{d.desc}</p>
      {/* REQUISITS D'ACCÉS */}
      <div style={{marginBottom:16,padding:"12px 16px",background:"rgba(69,123,157,0.1)",borderRadius:10,border:"1px solid rgba(69,123,157,0.2)"}}>
        <div style={{fontSize:11,color:"#A8DADC",textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6,fontWeight:700}}>📋 Requisits d'accés</div>
        <div style={{fontSize:13,color:"rgba(241,250,238,0.8)",lineHeight:1.6}}>{d.acces}</div>
      </div>
      {/* PONDERACIONS */}
      {d.pond.length>0&&<div style={{marginBottom:16,padding:"12px 16px",background:"rgba(42,157,143,0.08)",borderRadius:10,border:"1px solid rgba(42,157,143,0.2)"}}>
        <div style={{fontSize:11,color:"#2A9D8F",textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:8,fontWeight:700}}>📈 Matèries que pugen nota (ponderen ×0,2 a la PAU 2026)</div>
        <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>
          {d.pond.map((m,i)=><span key={i} style={{fontSize:12,fontWeight:700,color:"#F1FAEE",background:"rgba(42,157,143,0.25)",padding:"4px 10px",borderRadius:6}}>{m}</span>)}
        </div>
        <a href={POND_PDF} target="_blank" rel="noopener noreferrer" onClick={e=>e.stopPropagation()} style={{fontSize:11,color:"#A8DADC",marginTop:8,display:"inline-block",textDecoration:"none",fontWeight:500}}>
          Taula completa de ponderacions 2026 (PDF oficial) →
        </a>
      </div>}
      {/* NOTES DE TALL */}
      {d.nt.length>0&&<div style={{marginBottom:16}}>
        <div style={{fontSize:11,color:"rgba(241,250,238,0.4)",textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:8}}>Notes de tall 2025-26 (1a assignació)</div>
        <div style={{display:"flex",gap:8,flexWrap:"wrap"}}>
          {d.nt.map((n,i)=><div key={i} style={{background:"rgba(255,255,255,0.06)",borderRadius:8,padding:"8px 12px",display:"flex",alignItems:"baseline",gap:6}}>
            <span style={{fontSize:12,color:"rgba(241,250,238,0.5)",fontWeight:600}}>{n.u}</span>
            <span style={{fontSize:16,fontWeight:800,color:parseFloat(n.n)>=10?"#E63946":parseFloat(n.n)>=7?"#E9C46A":"#2A9D8F"}}>{n.n}</span>
          </div>)}
        </div>
        {link&&<a href={link} target="_blank" rel="noopener noreferrer" onClick={e=>e.stopPropagation()} style={{fontSize:12,color:"#A8DADC",marginTop:8,display:"inline-block",textDecoration:"none",fontWeight:600}}>Totes les notes a notesdetall.cat →</a>}
      </div>}
      {/* GRID INFO */}
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
        {[["On s'imparteix",d.uni],["Durada",d.dur],["Demanda",d.dem],["Contracte indefinit",d.ind+"%"],
          d.sat!==null?["Satisfacció estudis",d.sat+"/10"]:["Tipus","Cicle Formatiu de Grau Superior"],
          ["Sou vs mitjana",`${sd.pos?"+":""}${fmt(sd.d)} (${sd.pos?"+":""}${sd.p}%)`]
        ].map(([l,v],i)=>
          <div key={i} style={{background:"rgba(255,255,255,0.04)",borderRadius:10,padding:14}}>
            <div style={{fontSize:11,color:"rgba(241,250,238,0.4)",textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:4}}>{l}</div>
            <div style={{fontSize:13,color:i===5?(sd.pos?"#2A9D8F":"#E63946"):"#F1FAEE",fontWeight:i===5?700:400}}>{v}</div>
          </div>)}
      </div>
      <div style={{marginTop:16}}>
        <div style={{fontSize:11,color:"rgba(241,250,238,0.4)",marginBottom:6}}>SOU EN CONTEXT (mitjana {fp?"CFGS":"graduats"}: {fmt(d.ref)})</div>
        <div style={{position:"relative",height:20,background:"rgba(255,255,255,0.06)",borderRadius:10}}>
          <div style={{position:"absolute",left:0,top:0,height:"100%",width:`${Math.min((d.sou/mx)*100,100)}%`,background:`linear-gradient(90deg,${a.color}88,${a.color})`,borderRadius:10,transition:"width 1s ease"}}/>
          <div style={{position:"absolute",left:`${(d.ref/mx)*100}%`,top:-4,height:28,width:2,background:"rgba(241,250,238,0.5)",borderRadius:1}}/>
        </div>
      </div>
      {fp&&<div style={{marginTop:12,padding:"8px 12px",background:"rgba(233,196,106,0.08)",borderRadius:8,border:"1px solid rgba(233,196,106,0.15)"}}>
        <p style={{fontSize:11,color:"rgba(233,196,106,0.8)",lineHeight:1.5,margin:0}}>⚠️ Sous FP: estimació basada en l'estudi d'Inserció Laboral dels Ensenyaments Professionals 2024 (Generalitat + Consell de Cambres). No es disposa de dades de satisfacció equivalents a les dels graus.</p>
      </div>}
    </div>}
  </div>;
}

export default function App(){
  const[scr,setScr]=useState("intro");const[cq,setCq]=useState(0);const[ans,setAns]=useState([]);const[res,setRes]=useState(null);const[exp,setExp]=useState(null);const[fa,setFa]=useState("all");const[sb,setSb]=useState("match");const[tf,setTf]=useState("tots");const[sq,setSq]=useState("");
  const[showTop,setShowTop]=useState(false);const topRef=useRef(null);
  useEffect(()=>{const h=()=>setShowTop(window.scrollY>600);window.addEventListener("scroll",h,{passive:true});return()=>window.removeEventListener("scroll",h);},[]);
  function scrollTop(){topRef.current?topRef.current.scrollIntoView({behavior:"smooth"}):window.scrollTo({top:0,behavior:"smooth"});}
  function onAns(o){const na=[...ans,o];setAns(na);if(cq<QS.length-1)setCq(cq+1);else{const as=calc(na);setRes({as,degrees:topD(as,tf)});setScr("results");}}
  function restart(){setScr("intro");setCq(0);setAns([]);setRes(null);setExp(null);setFa("all");setSb("match");setTf("tots");setSq("");}
  function browse(){setRes({as:AREAS.map(a=>[a.id,1]),degrees:D});setFa("all");setSq("");setScr("browse");}
  function onTf(t){setTf(t);if(scr==="results"&&res)setRes({...res,degrees:topD(res.as,t)});}
  function norm(s){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();}
  function matchSearch(d){if(!sq.trim())return true;const q=norm(sq);const area=AREAS.find(x=>x.id===d.area);return norm(d.name).includes(q)||norm(d.desc).includes(q)||norm(area?.name||"").includes(q)||norm(d.uni).includes(q)||(d.pond||[]).some(p=>norm(p).includes(q));}
  const all=(scr==="browse"?(fa==="all"?D:D.filter(d=>d.area===fa)).filter(d=>tf==="tots"||d.type===tf):res?.degrees?.filter(d=>tf==="tots"||d.type===tf)||[]).filter(matchSearch);
  const sorted=sb==="match"?all:[...all].sort((a,b)=>sb==="sou"?b.sou-a.sou:sb==="ocupabilitat"?b.af-a.af:sb==="satisfaccio"?(b.sat||0)-(a.sat||0):0);
  const va=scr==="browse"?AREAS.filter(a=>D.some(d=>d.area===a.id&&(tf==="tots"||d.type===tf))):AREAS;

  return <div style={{minHeight:"100vh",background:"#0B1A2B",color:"#F1FAEE",fontFamily:"'DM Sans',sans-serif",position:"relative",overflow:"hidden"}}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700;800;900&family=DM+Sans:wght@300;400;500;600;700;800&display=swap');*{box-sizing:border-box;margin:0;padding:0}.dc:hover{background:rgba(255,255,255,0.07)!important;border-color:rgba(255,255,255,0.15)!important;transform:translateY(-2px);box-shadow:0 8px 32px rgba(0,0,0,0.3)}.ob{transition:all .25s ease;cursor:pointer}.ob:hover{background:rgba(255,255,255,0.12)!important;border-color:rgba(255,255,255,0.25)!important;transform:translateX(6px)}.fi{animation:fi .6s ease forwards;opacity:0}@keyframes fi{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}.pg{animation:pg 3s ease-in-out infinite}@keyframes pg{0%,100%{opacity:.3}50%{opacity:.6}}.ch{transition:all .2s ease;cursor:pointer;border:none;outline:none}.ch:hover{background:rgba(255,255,255,0.15)!important}::-webkit-scrollbar{width:6px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,0.15);border-radius:3px}a.ll{color:#A8DADC;text-decoration:none;font-weight:600}a.ll:hover{text-decoration:underline;color:#F1FAEE}input::placeholder{color:rgba(241,250,238,0.3)}`}</style>
    <div className="pg" style={{position:"fixed",top:"-30%",right:"-20%",width:"60vw",height:"60vw",borderRadius:"50%",background:"radial-gradient(circle,rgba(42,157,143,0.15) 0%,transparent 70%)",pointerEvents:"none"}}/>
    <div className="pg" style={{position:"fixed",bottom:"-20%",left:"-15%",width:"50vw",height:"50vw",borderRadius:"50%",background:"radial-gradient(circle,rgba(230,57,70,0.1) 0%,transparent 70%)",pointerEvents:"none",animationDelay:"1.5s"}}/>

    {scr==="intro"&&<div className="fi" style={{maxWidth:720,margin:"0 auto",padding:"80px 24px",textAlign:"center"}}>
      <div style={{fontSize:13,letterSpacing:"0.2em",textTransform:"uppercase",color:"#2A9D8F",fontWeight:600,marginBottom:24}}>Orientació · Graus i FP · Catalunya</div>
      <h1 style={{fontSize:"clamp(36px,7vw,64px)",fontWeight:900,fontFamily:"'Playfair Display',serif",lineHeight:1.1,marginBottom:20,background:"linear-gradient(135deg,#F1FAEE 0%,#A8DADC 50%,#2A9D8F 100%)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>Què vols estudiar?</h1>
      <p style={{fontSize:18,color:"rgba(241,250,238,0.6)",lineHeight:1.7,maxWidth:540,margin:"0 auto 40px"}}>Descobreix els <strong style={{color:"#F1FAEE"}}>graus universitaris</strong> i els <strong style={{color:"#F1FAEE"}}>cicles formatius de grau superior (FP)</strong> de Catalunya amb dades reals de sou, ocupabilitat, requisits d'accés i matèries que pugen nota.</p>
      <div style={{display:"flex",flexDirection:"column",gap:14,alignItems:"center"}}>
        <button onClick={()=>setScr("quiz")} style={{background:"linear-gradient(135deg,#2A9D8F,#457B9D)",color:"#F1FAEE",border:"none",padding:"16px 48px",borderRadius:12,fontSize:17,fontWeight:700,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",transition:"all 0.3s ease",boxShadow:"0 4px 24px rgba(42,157,143,0.3)"}} onMouseOver={e=>e.target.style.transform="scale(1.04)"} onMouseOut={e=>e.target.style.transform="scale(1)"}>Comença el test d'orientació</button>
        <button onClick={browse} style={{background:"transparent",color:"rgba(241,250,238,0.6)",border:"1px solid rgba(255,255,255,0.15)",padding:"12px 36px",borderRadius:10,fontSize:14,fontWeight:500,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",transition:"all 0.3s ease"}} onMouseOver={e=>{e.target.style.borderColor="rgba(255,255,255,0.3)";e.target.style.color="#F1FAEE"}} onMouseOut={e=>{e.target.style.borderColor="rgba(255,255,255,0.15)";e.target.style.color="rgba(241,250,238,0.6)"}}>Explora tots els graus i cicles</button>
      </div>
      <div style={{marginTop:60,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:12,opacity:0.5}}>
        {[{n:"142",l:"Graus i CFGS"},{n:"30.976 €",l:"Sou mitjà graduats"},{n:"18.500 €",l:"Sou mitjà CFGS"},{n:"54,4%",l:"Inserció FP (<1 any)"}].map((s,i)=><div key={i} style={{textAlign:"center"}}><div style={{fontSize:20,fontWeight:800,color:"#F1FAEE"}}>{s.n}</div><div style={{fontSize:11,color:"rgba(241,250,238,0.5)",marginTop:2}}>{s.l}</div></div>)}
      </div>
      <div style={{marginTop:48,padding:16,background:"rgba(255,255,255,0.03)",borderRadius:10,border:"1px solid rgba(255,255,255,0.06)"}}>
        <p style={{fontSize:11,color:"rgba(241,250,238,0.35)",lineHeight:1.6}}>Dades graus: Fundació CYD 2025, U-Ranking FBBVA-Ivie, INE. Notes de tall: Generalitat de Catalunya (1a assignació 2025-26). Ponderacions: Comissió d'Accés i Afers Estudiantils (PAU 2026). Dades FP: Inserció Laboral Ensenyaments Professionals 2024 (Consell de Cambres + Generalitat). Elaborat per <a href="https://www.linkedin.com/in/jordi-martinez-llorente/" target="_blank" rel="noopener noreferrer" className="ll">Jordi Martínez-Llorente</a></p>
      </div>
    </div>}

    {scr==="quiz"&&<div className="fi" style={{maxWidth:640,margin:"0 auto",padding:"60px 24px"}}>
      <div style={{width:"100%",height:6,background:"rgba(255,255,255,0.15)",borderRadius:3,overflow:"hidden"}}><div style={{width:`${(cq/QS.length)*100}%`,height:"100%",background:"linear-gradient(90deg,#E63946,#F4A261,#2A9D8F)",borderRadius:3,transition:"width 0.5s cubic-bezier(.4,0,.2,1)"}}/></div>
      <div style={{fontSize:12,color:"rgba(241,250,238,0.4)",textAlign:"center",marginTop:12,fontWeight:500}}>Pregunta {cq+1} de {QS.length}</div>
      <div key={cq} className="fi" style={{marginTop:48}}>
        <h2 style={{fontSize:28,fontWeight:700,fontFamily:"'Playfair Display',serif",textAlign:"center",lineHeight:1.4,marginBottom:36}}>{QS[cq].text}</h2>
        <div style={{display:"flex",flexDirection:"column",gap:12}}>
          {QS[cq].opts.map((o,i)=><button key={i} className="ob fi" style={{animationDelay:`${(i+1)*0.1}s`,display:"flex",alignItems:"center",gap:16,width:"100%",padding:"18px 24px",background:"rgba(255,255,255,0.04)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:14,color:"#F1FAEE",fontSize:16,fontWeight:500,textAlign:"left",fontFamily:"'DM Sans',sans-serif"}} onClick={()=>onAns(o)}>
            <span style={{width:32,height:32,borderRadius:8,background:"rgba(42,157,143,0.15)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:700,color:"#2A9D8F",flexShrink:0}}>{String.fromCharCode(65+i)}</span>{o.text}
          </button>)}
        </div>
      </div>
    </div>}

    {(scr==="results"||scr==="browse")&&<div ref={topRef} className="fi" style={{maxWidth:860,margin:"0 auto",padding:"48px 24px 80px"}}>
      {scr==="results"&&res&&<div style={{textAlign:"center",marginBottom:32}}>
        <div style={{fontSize:12,letterSpacing:"0.15em",color:"#2A9D8F",fontWeight:600,textTransform:"uppercase",marginBottom:12}}>Resultats del test</div>
        <h2 style={{fontSize:32,fontWeight:800,fontFamily:"'Playfair Display',serif",marginBottom:16}}>Les teves àrees top</h2>
        <div style={{display:"flex",justifyContent:"center",gap:10,flexWrap:"wrap",marginBottom:8}}>
          {res.as.slice(0,3).map(([id],i)=>{const a=AREAS.find(x=>x.id===id);return <div key={id} className="fi" style={{animationDelay:`${(i+1)*0.1}s`,padding:"10px 18px",borderRadius:12,background:`${a.color}22`,border:`1px solid ${a.color}44`,display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:18}}>{a.icon}</span><span style={{fontWeight:700,fontSize:14,color:a.color}}>{a.name}</span></div>;})}
        </div>
      </div>}
      {scr==="browse"&&<div style={{textAlign:"center",marginBottom:28}}><h2 style={{fontSize:32,fontWeight:800,fontFamily:"'Playfair Display',serif",marginBottom:8}}>Tots els estudis de Catalunya</h2><p style={{fontSize:14,color:"rgba(241,250,238,0.5)"}}>{D.length} graus universitaris i CFGS</p></div>}
      {/* CERCADOR */}
      <div style={{maxWidth:480,margin:"0 auto 20px",position:"relative"}}>
        <div style={{position:"absolute",left:16,top:"50%",transform:"translateY(-50%)",fontSize:18,opacity:0.4,pointerEvents:"none"}}>🔍</div>
        <input type="text" value={sq} onChange={e=>setSq(e.target.value)} placeholder="Cerca per nom, àrea, universitat o matèria..." style={{width:"100%",padding:"14px 16px 14px 46px",background:"rgba(255,255,255,0.06)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:12,color:"#F1FAEE",fontSize:15,fontFamily:"'DM Sans',sans-serif",outline:"none",transition:"border-color 0.2s ease"}} onFocus={e=>e.target.style.borderColor="rgba(42,157,143,0.5)"} onBlur={e=>e.target.style.borderColor="rgba(255,255,255,0.1)"}/>
        {sq&&<button onClick={()=>setSq("")} style={{position:"absolute",right:12,top:"50%",transform:"translateY(-50%)",background:"rgba(255,255,255,0.1)",border:"none",borderRadius:"50%",width:24,height:24,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",color:"rgba(241,250,238,0.6)",fontSize:14,fontWeight:700}}>✕</button>}
      </div>
      <div style={{display:"flex",justifyContent:"center",gap:0,marginBottom:20}}>
        {[{id:"tots",l:"Tots"},{id:"grau",l:"🎓 Graus"},{id:"cfgs",l:"🔧 FP (CFGS)"}].map((t,i)=><button key={t.id} className="ch" onClick={()=>onTf(t.id)} style={{padding:"10px 20px",fontSize:14,fontWeight:700,fontFamily:"'DM Sans',sans-serif",background:tf===t.id?"rgba(42,157,143,0.25)":"rgba(255,255,255,0.04)",color:tf===t.id?"#2A9D8F":"rgba(241,250,238,0.5)",borderRadius:i===0?"10px 0 0 10px":i===2?"0 10px 10px 0":"0",border:tf===t.id?"1px solid rgba(42,157,143,0.4)":"1px solid rgba(255,255,255,0.08)"}}>{t.l}</button>)}
      </div>
      {scr==="browse"&&<div style={{display:"flex",gap:8,flexWrap:"wrap",justifyContent:"center",marginBottom:20}}>
        <button className="ch" onClick={()=>setFa("all")} style={{padding:"7px 14px",borderRadius:20,fontSize:12,fontWeight:600,fontFamily:"'DM Sans',sans-serif",background:fa==="all"?"rgba(42,157,143,0.3)":"rgba(255,255,255,0.06)",color:fa==="all"?"#2A9D8F":"rgba(241,250,238,0.6)"}}>Tots</button>
        {va.map(a=><button key={a.id} className="ch" onClick={()=>setFa(a.id)} style={{padding:"7px 14px",borderRadius:20,fontSize:12,fontWeight:600,fontFamily:"'DM Sans',sans-serif",background:fa===a.id?`${a.color}33`:"rgba(255,255,255,0.06)",color:fa===a.id?a.color:"rgba(241,250,238,0.6)"}}>{a.icon} {a.name}</button>)}
      </div>}
      <div style={{display:"flex",gap:8,justifyContent:"center",marginBottom:24,flexWrap:"wrap"}}>
        <span style={{fontSize:13,color:"rgba(241,250,238,0.4)",alignSelf:"center",marginRight:4}}>Ordenar:</span>
        {[{id:"match",l:scr==="results"?"Recomanació":"Per defecte"},{id:"sou",l:"Sou"},{id:"ocupabilitat",l:"Ocupabilitat"},{id:"satisfaccio",l:"Satisfacció"}].map(s=><button key={s.id} className="ch" onClick={()=>setSb(s.id)} style={{padding:"6px 14px",borderRadius:16,fontSize:12,fontWeight:600,fontFamily:"'DM Sans',sans-serif",background:sb===s.id?"rgba(255,255,255,0.12)":"rgba(255,255,255,0.04)",color:sb===s.id?"#F1FAEE":"rgba(241,250,238,0.5)"}}>{s.l}</button>)}
      </div>
      <div style={{textAlign:"center",fontSize:13,color:"rgba(241,250,238,0.35)",marginBottom:16}}>{sorted.length} resultats</div>
      <div style={{display:"flex",flexDirection:"column",gap:12}}>{sorted.map((d,i)=><Card key={d.name+d.area+d.type} d={d} expanded={exp===d.name+d.type} onToggle={()=>setExp(exp===d.name+d.type?null:d.name+d.type)}/>)}</div>
      {sorted.length===0&&<div style={{textAlign:"center",padding:40,color:"rgba(241,250,238,0.4)"}}>{sq?`Cap resultat per "${sq}". Prova amb un altre terme.`:"No hi ha resultats amb aquests filtres."}</div>}
      <div style={{display:"flex",justifyContent:"center",gap:16,marginTop:40,flexWrap:"wrap"}}>
        <button onClick={restart} style={{background:"linear-gradient(135deg,#2A9D8F,#457B9D)",color:"#F1FAEE",border:"none",padding:"14px 32px",borderRadius:10,fontSize:15,fontWeight:700,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>Tornar a fer el test</button>
        {scr==="results"&&<button onClick={browse} style={{background:"transparent",border:"1px solid rgba(255,255,255,0.15)",color:"rgba(241,250,238,0.7)",padding:"14px 32px",borderRadius:10,fontSize:15,fontWeight:500,cursor:"pointer",fontFamily:"'DM Sans',sans-serif"}}>Explorar tots els estudis</button>}
      </div>
      <div style={{marginTop:48,padding:16,background:"rgba(255,255,255,0.03)",borderRadius:10,border:"1px solid rgba(255,255,255,0.06)",textAlign:"center"}}>
        <p style={{fontSize:11,color:"rgba(241,250,238,0.3)",lineHeight:1.6}}>Dades graus: Fundació CYD 2025 (sous = BMC 4 anys post-grau), U-Ranking FBBVA-Ivie, satisfacció: enquestes FBBVA i LAB4Future/Wuolah. Notes de tall: 1a assignació 2025-26 (Generalitat, universitats.gencat.cat). Ponderacions: taula oficial PAU 2026 aprovada per la Comissió d'Accés i Afers Estudiantils del CIC. Dades FP: Inserció Laboral Ensenyaments Professionals 2024 (Consell de Cambres + Dept. Educació i FP). Sous CFGS estimats a partir dels trams salarials de l'estudi.<br/>Elaborat per <a href="https://www.linkedin.com/in/jordi-martinez-llorente/" target="_blank" rel="noopener noreferrer" className="ll">Jordi Martínez-Llorente</a></p>
      </div>
    </div>}

    {showTop&&<button onClick={scrollTop} style={{position:"fixed",bottom:28,right:28,width:48,height:48,borderRadius:"50%",background:"rgba(42,157,143,0.9)",border:"none",color:"#F1FAEE",fontSize:22,fontWeight:800,cursor:"pointer",boxShadow:"0 4px 20px rgba(0,0,0,0.4)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:50,backdropFilter:"blur(8px)",transition:"all 0.3s ease",animation:"fi 0.3s ease"}} onMouseOver={e=>e.currentTarget.style.transform="scale(1.12)"} onMouseOut={e=>e.currentTarget.style.transform="scale(1)"} aria-label="Tornar a dalt">↑</button>}
  </div>;
}
